// Slot-based closureless dispatch POC.
//
// -- Background --
//
// The Slot trait uses Brand as a trait parameter (not an associated
// type). For closure-taking operations like `map` and `bind`, the
// closure's input type pins A, which disambiguates Brand via the Slot
// bound. But closureless operations (`alt`, `join`, `apply_first`,
// `apply_second`) have no closure. Brand must resolve solely from
// FA's single Slot impl (for single-brand types) or fail (for
// multi-brand types).
//
// With the old InferableBrand, Brand was an associated type, so the
// solver committed it directly from FA. With Slot, Brand is a trait
// parameter. The question is whether the solver commits Brand from a
// single Slot impl when no other constraint drives it.
//
// -- Hypothesis --
//
// For single-brand types, the solver resolves Brand from the unique
// Slot impl without needing a closure. For multi-brand types, the
// solver reports ambiguity (same as today). Both `alt` (flat
// containers) and `join` (nested containers) work.
//
// -- Finding --
//
// CONFIRMED. All 11 tests pass on stable rustc: Val and Ref for both
// alt (flat, 5 tests) and join (nested, 6 tests) with Option and Vec.
// The solver resolves Brand from the single Slot impl without a
// closure. For join, the extra MidA type parameter (representing the
// inner container type) is inferred correctly alongside Brand.

#![allow(unused_imports, reason = "Kind is used inside Apply! macro expansion")]

// -------------------------------------------------------------------------
// Use the production Slot trait (generated by trait_kind!).
// -------------------------------------------------------------------------
use {
	fp_library::{
		brands::{
			OptionBrand,
			VecBrand,
		},
		dispatch::{
			Ref,
			Val,
			alt::AltDispatch,
			semimonad::JoinDispatch,
		},
		kinds::{
			Kind_cdc7cd43dac7585f,
			Slot_cdc7cd43dac7585f,
		},
	},
	fp_macros::{
		Apply,
		Kind,
	},
};

// -------------------------------------------------------------------------
// alt: Slot resolves Brand from FA alone, no closure.
// -------------------------------------------------------------------------

pub fn alt<'a, FA, A: 'a + Clone, Brand>(
	fa1: FA,
	fa2: FA,
) -> Apply!(<Brand as Kind!(type Of<'a, T: 'a>: 'a;)>::Of<'a, A>)
where
	Brand: Kind_cdc7cd43dac7585f,
	FA: Slot_cdc7cd43dac7585f<'a, Brand, A>
		+ AltDispatch<'a, Brand, A, <FA as Slot_cdc7cd43dac7585f<'a, Brand, A>>::Marker>, {
	fa1.dispatch(fa2)
}

// -------------------------------------------------------------------------
// join: Slot resolves Brand from FA, inner type is itself branded.
//
// The extra `MidA` type parameter represents the inner container type
// (e.g., Option<i32> for Option<Option<i32>>). It is inferred from
// the Slot decomposition and never specified by the caller.
// -------------------------------------------------------------------------

pub fn join<'a, FA, A: 'a, Brand, MidA: 'a>(
	mma: FA
) -> Apply!(<Brand as Kind!(type Of<'a, T: 'a>: 'a;)>::Of<'a, A>)
where
	Brand: Kind_cdc7cd43dac7585f,
	FA: Slot_cdc7cd43dac7585f<'a, Brand, MidA>
		+ JoinDispatch<'a, Brand, A, <FA as Slot_cdc7cd43dac7585f<'a, Brand, MidA>>::Marker>, {
	mma.dispatch()
}

// -------------------------------------------------------------------------
// Tests: alt (Val and Ref, single-brand).
// -------------------------------------------------------------------------

#[test]
fn alt_val_option_none_some() {
	assert_eq!(alt(None::<i32>, Some(5)), Some(5));
}

#[test]
fn alt_val_option_some_some() {
	assert_eq!(alt(Some(3), Some(5)), Some(3));
}

#[test]
fn alt_val_vec() {
	assert_eq!(alt(vec![1, 2], vec![3, 4]), vec![1, 2, 3, 4]);
}

#[test]
fn alt_ref_option() {
	let a: Option<i32> = None;
	let b = Some(5);
	assert_eq!(alt(&a, &b), Some(5));
}

#[test]
fn alt_ref_vec() {
	let x = vec![1, 2];
	let y = vec![3, 4];
	assert_eq!(alt(&x, &y), vec![1, 2, 3, 4]);
}

// -------------------------------------------------------------------------
// Tests: join (Val and Ref, single-brand).
// -------------------------------------------------------------------------

#[test]
fn join_val_option_some() {
	assert_eq!(join(Some(Some(5))), Some(5));
}

#[test]
fn join_val_option_none_outer() {
	assert_eq!(join(None::<Option<i32>>), None);
}

#[test]
fn join_val_option_none_inner() {
	assert_eq!(join(Some(None::<i32>)), None);
}

#[test]
fn join_val_vec() {
	assert_eq!(join(vec![vec![1, 2], vec![3, 4]]), vec![1, 2, 3, 4]);
}

#[test]
fn join_ref_option() {
	let x = Some(Some(5));
	assert_eq!(join(&x), Some(5));
	assert_eq!(x, Some(Some(5)));
}

#[test]
fn join_ref_vec() {
	let x = vec![vec![1, 2], vec![3, 4]];
	assert_eq!(join(&x), vec![1, 2, 3, 4]);
	assert_eq!(x, vec![vec![1, 2], vec![3, 4]]);
}
